version: "3.8"

services:
  cpanel-backend:
    build:
      context: ./Cpanel/auth-server
    container_name: cpanel-backend
    ports:
      - "5002:5000"
    env_file:
      - /opt/envs/cpanel-backend.env
    networks:
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cpanel-frontend:
    build:
      context: ./Cpanel/CpanelWeb
      args:
        VITE_CPANEL_API_BASE_URL: ${VITE_CPANEL_API_BASE_URL}
        VITE_MAIN_PORTAL_URL: ${VITE_MAIN_PORTAL_URL}
    container_name: cpanel-frontend
    ports:
      - "4002:4000"
    env_file:
      - /opt/envs/cpanel-frontend.env
    networks:
      - webnet

  developer-backend:
    build:
      context: ./developerWeb/Backend
    container_name: developer-backend
    ports:
      - "5001:5000"
    env_file:
      - /opt/envs/dev-backend.env
    networks:
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  developer-frontend:
    build:
      context: ./developerWeb/authServerWeb
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_URL: ${VITE_API_URL}
        VITE_SUPPORT_EMAIL: ${VITE_SUPPORT_EMAIL}
    container_name: developer-frontend
    ports:
      - "4001:4000"
    env_file:
      - /opt/envs/dev-frontend.env
    networks:
      - webnet

networks:
  webnet:
    external: true
